### ISSUE TITLE
Problemi con resources_rc

### ISSUE THREAD

**Issue by pyarchinit** [pyarchinit/vector_georeferencer_plugin#5]
Ciao Luca e Giuliano,

ho installato la nuova versione di vectorgeoref, ma mi torna questi errori :

Impossibile caricare il plugin vectGeoref a causa di errore chiamando il metodo classFactory()

Traceback (most recent call last):
  File "c:/Users/rrr/PROGRA~1/QGISVA~1/apps/qgis/./python\qgis\utils.py", line 204, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/rrr/.qgis2/python/plugins\vectGeoref__init__.py", line 26, in classFactory
    from vectorgeoref import VectorGeoref
  File "c:/Users/rrr/PROGRA~1/QGISVA~1/apps/qgis/./python\qgis\utils.py", line 453, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/rrr/.qgis2/python/plugins\vectGeoref\vectorgeoref.py", line 32, in 
    import resources_rc
  File "c:/Users/rrr/PROGRA~1/QGISVA~1/apps/qgis/./python\qgis\utils.py", line 453, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: No module named resources_rc

Versione Python:
2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]

Versione di QGIS:
2.2.0-Valmiera Valmiera, c3a2817

Ho visto che la directory del plugin e'  "vectGeoref"  mentre il plugin  a volte si chiama    "vectorgeoref" ,   a volte "VectorGeoref"   ecc...

Ho sperimentato coi miei plugin che questa differenza di maiuscole/minuscole  da problemi  (su windows...? ).

Potete verificare ?

Ciao

Roberto

**Comment by antoniocittadino** [comment]
Ho lo stesso problema, e' stato risolto ?
Grazie
Antonio Cittadino
